### ISSUE TITLE
Strip away wrapping tags and surrounding empty space

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/relaton-data-ids#4]
Under `abstract > content` we need to strip away the wrapping (empty) tags and the surrounding empty space:

https://github.com/ietf-ribose/relaton-data-ids/blob/d7fd11beadea199a170cdccde011d93cf4fee1e9/data/DRAFT-3GPP-COLLABORATION-01.yaml#L82-L85

==>

```yaml
abstract:
  content: "This document describes the standardization collaboration between
    3GPP and IETF.  This memo provides information for the Internet community."
```
